name: 'Stream 9 multi-arch image build'
 
on:
  workflow_dispatch:
    # inputs:
    #   go_version:
    #     description: 'Go version to build in format X.Y.Z'
    #     required: false
    #     default: ''
  push:
    paths:
      - 'Dockerfile.stream9'
      - '.github/workflows/stream9_multi_arch_image_build.yml'
  schedule:
    - cron: '0 0 * * 6'
  pull_request:
    paths:
      - 'Dockerfile.stream9'
      - '.github/workflows/stream9_multi_arch_image_build.yml'
jobs:
  multiarch-build:
    runs-on: ubuntu-latest
    steps:
      - name: add checkout action...
        uses: actions/checkout@v2
 
      - name: configure QEMU action...
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
 
      - name: configure Docker Buildx...
        id: docker_buildx
        uses: docker/setup-buildx-action@master
 
      - name: login to Quay.io...
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_PUBLISH_ROBOT }}
          password: ${{ secrets.QUAY_PUBLISH_TOKEN }}
 
      - name: build Multi-arch images...
        uses: docker/build-push-action@v3.3.0
        with:
          builder: ${{ steps.docker_buildx.outputs.name }}
          context: .
          file: ./Dockerfile.stream9
          platforms: linux/amd64,linux/ppc64le,linux/arm64,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/konveyor/builder:stream9-latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          provenance: false
      - name: get go version
        if: github.event_name != 'pull_request'
        id: go_version_patch
        run: | 
          echo "patch_version=$(docker run --rm quay.io/konveyor/builder:stream9-latest${{ github.event.inputs.go_version }} go version | cut -c 14-19)" >> $GITHUB_ENV
      - name: get go version
        if: github.event_name != 'pull_request'
        id: go_version_minor
        run: | 
          echo "minor_version=$(docker run --rm quay.io/konveyor/builder:stream9-latest${{ github.event.inputs.go_version }} go version | cut -c 14-17)" >> $GITHUB_ENV
      - name: reuse cache to push tagged Multi-arch images...
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3.3.0
        with:
          builder: ${{ steps.docker_buildx.outputs.name }}
          context: .
          file: ./Dockerfile.stream9
          platforms: linux/amd64,linux/ppc64le,linux/arm64,linux/s390x
          push: true
          tags: quay.io/konveyor/builder:stream9-v${{ env.minor_version }},quay.io/konveyor/builder:stream9-v${{ env.patch_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          provenance: false
